version: '3'
services:

  db:
    image: mdillon/postgis
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: 'nens'
      POSTGRES_PASSWORD: 'nens'
      POSTGRES_DB: '{{ cookiecutter.package_name }}'

  web:
    build: .
    user: $UID  # run `export UID` to make this work (or add to your .bashrc)
    command: "pipenv run python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    volumes:
      # do not use .:/code to circumvent a docker issue
      - ./:/code
      - $HOME/.cache/pipenv:/pipenv_cache
      - $SSH_AUTH_SOCK:/tmp/agent.sock
    depends_on:
      - db
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PIPENV_VENV_IN_PROJECT=1
      - PIPENV_CACHE_DIR=/pipenv_cache
      - SHELL=/bin/bash
      - SSH_AUTH_SOCK=/tmp/agent.sock
