version: '3'
services:

  db:
    image: mdillon/postgis:9.3-alpine
    environment:
      POSTGRES_USER: 'nens'
      POSTGRES_PASSWORD: 'nens'
      POSTGRES_DB: '{{ cookiecutter.package_name }}'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  web:
    build: .
    entrypoint: "pipenv run"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
{% if cookiecutter.celery == "yes" %}      - rabbit{% endif %}
{% if cookiecutter.celery == "yes" %}      - worker{% endif %}
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache:/home/nens/.cache  # shared cache

{% if cookiecutter.celery == "yes" %}
  worker:
    build: .
    entrypoint: "pipenv run"
    command: celery worker --app={{ cookiecutter.package_name }} --concurrency=1 --pidfile=var/celery.pid --loglevel=info --task-events
    depends_on:
      - db
      - rabbit
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache:/home/nens/.cache  # shared cache

  rabbit:
    image: rabbitmq
{% endif %}

volumes:
  pgdata:

#for local development, you may want to open some ports by adding a
#docker-compose.override.yml file with host:docker port mappings
#
#version: '3'
#services:
#
#  db:
#    ports:
#      - "5435:5432"
#
#  web:
#    ports:
#      - "5000:8000"
