version: '3'
services:

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: 'nens'
      POSTGRES_PASSWORD: 'nens'
      POSTGRES_DB: '{{ cookiecutter.package_name }}'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  web:
    build: .
    entrypoint: "pipenv run"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbitmq
{% if cookiecutter.celery == "yes" %}      - celery
{% endif %}    environment:
      - C_FORCE_ROOT=1
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache/pip:/home/nens/.cache/pip  # shared pip cache
      - ~/.cache/pipenv:/home/nens/.cache/pipenv  # shared pipenv cache

{% if cookiecutter.celery == "yes" %}  celery:
    build: .
    entrypoint: "pipenv run"
    command: celery worker --app={{ cookiecutter.package_name }} --concurrency=1 --pidfile=var/celery.pid --loglevel=info --task-events
    depends_on:
      - db
      - rabbitmq
    environment:
      - C_FORCE_ROOT=1
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PIPENV_VENV_IN_PROJECT=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache/pip:/home/nens/.cache/pip  # shared pip cache
      - ~/.cache/pipenv:/home/nens/.cache/pipenv  # shared pipenv cache{% endif %}

volumes:
  pgdata:

#for local development, you may want to open some ports by adding a
#docker-compose.override.yml file with host:docker port mappings
#
#version: '3'
#services:
#
#  db:
#    ports:
#      - "5435:5432"
#
#  web:
#    ports:
#      - "5000:8000"
