# Goal: do the root-related basic provisioning for a site (now: only this
# server). A buildout user is set up with ssh keys so that the relevant devs
# can ssh in as user buildout, which will be used by the deploy.yml script.
---
- name: provision server to prepare for the actual deployment
  hosts: web
  become: yes
  tasks:

    - name: Add build user and set an unusable password.
      user:
        name: "{{ build_user }}"
        password: '*'
        state: present
        shell: "/bin/bash"

    - name: "Add maintainers' ssh keys so they can log in as the build user."
      authorized_key:
        user: "{{ build_user }}"
        key: https://github.com/{{ item }}.keys
      with_items:
        - byrman
        - remcogerlich
        # - add your github username here

    - name: Install apt packages.
      apt: name={{ item }} state=latest
      with_items:
        - git
        - python3-dev
        - python3-pip
        - supervisor
        - memcached
        - nginx
        - libpq-dev       # for psycopg2 (postgres backend)
        # - libgdal-dev \       uncomment if the project requires pygdal
        # - libfreetype6-dev \  uncomment if the project requires matplotlib

    - name: Upgrade setuptools
      pip:
        name: setuptools
        state: latest

    - name: Install pip
      pip:
        name: pip
        version: 10.0.1

    - name: Install pipenv
      pip:
        name: pipenv
        version: 2018.5.18

    - name: Create the project path.
      file:
        path: "{{ project_path }}"
        state: directory
        mode: 0755
        owner: "{{ build_user }}"
        group: "{{ build_user }}"

    - name: "Look if nginx config already exists (you'll need to run deploy first!)"
      stat: path={{ project_path }}/etc/{{ site_name }}.nginx.conf
      register: nginx_conffile

    - name: Symlink nginx config, when available.
      file:
        src: {{ project_path }}/etc/{{ site_name }}.nginx.conf
        dest: /etc/nginx/sites-available/{{ site_name }}.nginx.conf
        state: link
      when: nginx_conffile.stat.exists

    - name: Enable nginx config, when available.
      file:
        src: /etc/nginx/sites-available/{{ site_name }}.nginx.conf
        dest: /etc/nginx/sites-enabled/{{ site_name }}.nginx.conf
        state: link
      when: nginx_conffile.stat.exists

    - name: Restart nginx.
      service: name=nginx state=reloaded
      when: nginx_conffile.stat.exists
